### ISSUE TITLE
Schedule purge error

### ISSUE THREAD

**Issue by spagnumkaren** [cskoglun/ciscodnacbackupctl#19]
I think there is something wrong with the schedule purge function. It looks like it is not updating the token.
The picture shows the purge is fine on the first day but every day after that shows the same error:
Cisco DNA Center isn't available - 401 Client Error: Unauthorized for url: https://192.168.31.101/api/system/v1/maglev/backup
![7fc76440-82e1-47eb-8033-f0f5cc5d6b31](https://user-images.githubusercontent.com/96144306/200779583-4ad8913a-f62e-4ebb-8fba-ee2b47ff4874.PNG)

If I run the manual purge it works fine so It is only the schedule purge that gets this error.
![a06e18c9-220e-4f8f-839b-84fe657118d5](https://user-images.githubusercontent.com/96144306/200779854-5a398602-b772-4407-a07f-f90a663dae10.PNG)

**Comment by robertcsapo** [comment]
It might be that the DNAC token isn't updated.
I've added the logs in the latest release, so that should help to pin point this issue

**Comment by robertcsapo** [comment]
Related to #26
