### ISSUE TITLE
Error while calling ciscodnacbackupctl using the v2 URL

### ISSUE THREAD

**Issue by abhi093** [cskoglun/ciscodnacbackupctl#21]
hello Developer,

We are receiving the below error while using the tool ciscodnacbackupctl for URL /dna/system/api/v2/auth/token. our DNA-C is now on v2 but the tool smoehow not using the v2 url to call the backup files and using the v1

Please modify the tool to use v2 URL ( /dna/system/api/v2/auth/token)

**Error:**
Max retries exceeded with url: /dna/system/api/v1/auth/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3aae321cd0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by abhi093** [comment]
@robertcsapo @cskoglun

**Comment by abhi093** [comment]
@carsten@anspach.de

**Comment by robertcsapo** [comment]
The latest version and documentation for Cisco DNA Center still uses /v1/
https://developer.cisco.com/docs/dna-center/#!authentication-api
