### ISSUE TITLE
Correct way to start Daemon on Ubuntu startup

### ISSUE THREAD

**Issue by ekrizon** [cskoglun/ciscodnacbackupctl#29]
(not traditionally a Linux guy so please bear with me)

I have done the following to start the service automatically when the server is restarted:

sudo crontab -e
@reboot ciscodnacbackupctl daemon start --keep 5

After a reboot if I do:
ciscodnacbackupctl daemon status

I can see the daemon is running. However leaving it for weeks and it does not purge any backups.

If I stop the daemon and start it manually, then leave it again. It correctly operates and purges the backups like it should. Just does not work when the daemon starts using the startup script (something different about how its starting??)

Am I doing something wrong? How do I correctly get this to start when the server does so I don't need to worry about it?

**Comment by robertcsapo** [comment]
Without any logs, it would be hard to find out the issue.
Have you checked ```/var/log/syslog``` ?
